# Generated by Django 5.0.3 on 2024-08-21 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='day_of_week',
        ),
    ]
