# Generated by Django 5.0.3 on 2024-08-22 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_alter_attendance_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='class_info',
        ),
    ]
