# Generated by Django 5.0.3 on 2024-08-22 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_class_subjects'),
        ('teacher', '0007_alter_attendance_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='class_info',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='classes.class'),
            preserve_default=False,
        ),
    ]
