# Generated by Django 5.0.3 on 2024-08-25 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0014_remove_attendance_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='class_info',
        ),
    ]
