# Generated by Django 5.0.3 on 2024-08-25 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_class_subjects'),
        ('teacher', '0015_remove_attendance_class_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='class_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='classes.class'),
        ),
    ]
