# Generated by Django 5.0.3 on 2024-08-27 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0018_attendance_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
    ]
