# Generated by Django 5.0.3 on 2024-08-27 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0021_attendance_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='status1',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='status10',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='status11',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='status12',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='status13',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='status14',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='status15',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='status16',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='status17',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='status18',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='status19',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='status2',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='status20',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='status21',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='status22',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='status3',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='status4',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='status5',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='status6',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='status7',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='status8',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='status9',
        ),
    ]
