# Generated by Django 5.0.3 on 2024-08-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0022_rename_status1_attendance_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='status',
            new_name='status1',
        ),
        migrations.AddField(
            model_name='attendance',
            name='status10',
            field=models.CharField(blank=True, choices=[('P', 'Present'), ('A', 'Absent'), ('D', 'Default')], default='D', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status11',
            field=models.CharField(blank=True, choices=[('P', 'Present'), ('A', 'Absent'), ('D', 'Default')], default='D', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status12',
            field=models.CharField(blank=True, choices=[('P', 'Present'), ('A', 'Absent'), ('D', 'Default')], default='D', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status13',
            field=models.CharField(blank=True, choices=[('P', 'Present'), ('A', 'Absent'), ('D', 'Default')], default='D', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status14',
            field=models.CharField(blank=True, choices=[('P', 'Present'), ('A', 'Absent'), ('D', 'Default')], default='D', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status15',
            field=models.CharField(blank=True, choices=[('P', 'Present'), ('A', 'Absent'), ('D', 'Default')], default='D', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status16',
            field=models.CharField(blank=True, choices=[('P', 'Present'), ('A', 'Absent'), ('D', 'Default')], default='D', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status17',
            field=models.CharField(blank=True, choices=[('P', 'Present'), ('A', 'Absent'), ('D', 'Default')], default='D', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status18',
            field=models.CharField(blank=True, choices=[('P', 'Present'), ('A', 'Absent'), ('D', 'Default')], default='D', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status19',
            field=models.CharField(blank=True, choices=[('P', 'Present'), ('A', 'Absent'), ('D', 'Default')], default='D', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status2',
            field=models.CharField(blank=True, choices=[('P', 'Present'), ('A', 'Absent'), ('D', 'Default')], default='D', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status20',
            field=models.CharField(blank=True, choices=[('P', 'Present'), ('A', 'Absent'), ('D', 'Default')], default='D', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status21',
            field=models.CharField(blank=True, choices=[('P', 'Present'), ('A', 'Absent'), ('D', 'Default')], default='D', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status22',
            field=models.CharField(blank=True, choices=[('P', 'Present'), ('A', 'Absent'), ('D', 'Default')], default='D', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status3',
            field=models.CharField(blank=True, choices=[('P', 'Present'), ('A', 'Absent'), ('D', 'Default')], default='D', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status4',
            field=models.CharField(blank=True, choices=[('P', 'Present'), ('A', 'Absent'), ('D', 'Default')], default='D', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status5',
            field=models.CharField(blank=True, choices=[('P', 'Present'), ('A', 'Absent'), ('D', 'Default')], default='D', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status6',
            field=models.CharField(blank=True, choices=[('P', 'Present'), ('A', 'Absent'), ('D', 'Default')], default='D', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status7',
            field=models.CharField(blank=True, choices=[('P', 'Present'), ('A', 'Absent'), ('D', 'Default')], default='D', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status8',
            field=models.CharField(blank=True, choices=[('P', 'Present'), ('A', 'Absent'), ('D', 'Default')], default='D', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status9',
            field=models.CharField(blank=True, choices=[('P', 'Present'), ('A', 'Absent'), ('D', 'Default')], default='D', max_length=1, null=True),
        ),
    ]
