# Generated by Django 5.0.3 on 2024-09-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0027_attendance_status23'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='exam',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='final_grade',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='first_test',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='second_test',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
