# Generated by Django 5.0.3 on 2024-09-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0028_alter_grade_comments_alter_grade_exam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='final_grade',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
