# Generated by Django 5.0.3 on 2024-09-08 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0033_grade_exam2_grade_first_test2_grade_grade2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='subject1',
            new_name='subject',
        ),
    ]
