# Generated by Django 5.0.3 on 2024-09-09 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_class_subjects'),
        ('teacher', '0034_rename_subject1_grade_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='class_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='classes.class'),
        ),
    ]
