# Generated by Django 5.0.3 on 2024-09-09 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_alter_teacher_subject'),
        ('classes', '0002_alter_class_subjects'),
        ('teacher', '0035_alter_grade_class_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=20)),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_class_info', to='classes.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_student', to='administration.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_subject', to='classes.subject')),
            ],
        ),
        migrations.CreateModel(
            name='FirstTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=20)),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firsttest_class_info', to='classes.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firsttest_student', to='administration.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firsttest_subject', to='classes.subject')),
            ],
        ),
        migrations.CreateModel(
            name='SecondTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=20)),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondtest_class_info', to='classes.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondtest_student', to='administration.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondtest_subject', to='classes.subject')),
            ],
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
