# Generated by Django 5.0.3 on 2024-09-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0036_exam_firsttest_secondtest_delete_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='out_of',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='firsttest',
            name='out_of',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='secondtest',
            name='out_of',
            field=models.IntegerField(default=100),
        ),
    ]
