# Generated by Django 5.0.3 on 2024-09-10 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0041_remove_firsttest_class_info_firsttest_teacher_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='class_info',
        ),
        migrations.RemoveField(
            model_name='secondtest',
            name='class_info',
        ),
        migrations.AddField(
            model_name='exam',
            name='teacher_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_teacher_class', to='teacher.teacherclass'),
        ),
        migrations.AddField(
            model_name='secondtest',
            name='teacher_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondtest_teacher_class', to='teacher.teacherclass'),
        ),
    ]
