# Generated by Django 5.0.3 on 2024-09-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_class_subjects'),
        ('teacher', '0042_remove_exam_class_info_remove_secondtest_class_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherclass',
            name='class_name',
        ),
        migrations.AddField(
            model_name='teacherclass',
            name='class_name',
            field=models.ManyToManyField(related_name='class_teacher_classes', to='classes.class'),
        ),
    ]
