# Generated by Django 5.0.3 on 2024-09-10 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_alter_teacher_subject'),
        ('classes', '0002_alter_class_subjects'),
        ('teacher', '0043_remove_teacherclass_class_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='term',
            field=models.CharField(choices=[('First Term', 'First Term'), ('Second Term', 'Second Term'), ('Third Term', 'Third Term')], default='First Term', max_length=20),
        ),
        migrations.AddField(
            model_name='exam',
            name='year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AddField(
            model_name='firsttest',
            name='term',
            field=models.CharField(choices=[('First Term', 'First Term'), ('Second Term', 'Second Term'), ('Third Term', 'Third Term')], default='First Term', max_length=20),
        ),
        migrations.AddField(
            model_name='firsttest',
            name='year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AddField(
            model_name='secondtest',
            name='term',
            field=models.CharField(choices=[('First Term', 'First Term'), ('Second Term', 'Second Term'), ('Third Term', 'Third Term')], default='First Term', max_length=20),
        ),
        migrations.AddField(
            model_name='secondtest',
            name='year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='exam',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_student', to='administration.student'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_subject', to='classes.subject'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='teacher_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_teacher_class', to='teacher.teacherclass'),
        ),
        migrations.AlterField(
            model_name='firsttest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_student', to='administration.student'),
        ),
        migrations.AlterField(
            model_name='firsttest',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_subject', to='classes.subject'),
        ),
        migrations.AlterField(
            model_name='firsttest',
            name='teacher_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_teacher_class', to='teacher.teacherclass'),
        ),
        migrations.AlterField(
            model_name='secondtest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_student', to='administration.student'),
        ),
        migrations.AlterField(
            model_name='secondtest',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_subject', to='classes.subject'),
        ),
        migrations.AlterField(
            model_name='secondtest',
            name='teacher_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_teacher_class', to='teacher.teacherclass'),
        ),
    ]
