# Generated by Django 5.0.3 on 2024-09-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0044_exam_term_exam_year_firsttest_term_firsttest_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='grade',
            field=models.CharField(choices=[('A', 'A (90% - 100%)'), ('B', 'B (80% - 89%)'), ('C', 'C (60% - 79%)'), ('D', 'D (0% - 59%)')], default='D', max_length=1),
        ),
        migrations.AddField(
            model_name='firsttest',
            name='grade',
            field=models.CharField(choices=[('A', 'A (90% - 100%)'), ('B', 'B (80% - 89%)'), ('C', 'C (60% - 79%)'), ('D', 'D (0% - 59%)')], default='D', max_length=1),
        ),
        migrations.AddField(
            model_name='secondtest',
            name='grade',
            field=models.CharField(choices=[('A', 'A (90% - 100%)'), ('B', 'B (80% - 89%)'), ('C', 'C (60% - 79%)'), ('D', 'D (0% - 59%)')], default='D', max_length=1),
        ),
    ]
