# Generated by Django 5.0.3 on 2024-09-12 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_alter_teacher_subject'),
        ('classes', '0002_alter_class_subjects'),
        ('teacher', '0045_exam_grade_firsttest_grade_secondtest_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firsttest',
            name='student',
        ),
        migrations.RemoveField(
            model_name='firsttest',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='firsttest',
            name='teacher_class',
        ),
        migrations.RemoveField(
            model_name='secondtest',
            name='student',
        ),
        migrations.RemoveField(
            model_name='secondtest',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='secondtest',
            name='teacher_class',
        ),
        migrations.CreateModel(
            name='StudentGradeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choose_exam', models.CharField(choices=[('First Test', 'First Test'), ('Second Test', 'Second Test'), ('Exam', 'Exam')], default='First Test', max_length=15)),
                ('term', models.CharField(choices=[('First Term', 'First Term'), ('Second Term', 'Second Term'), ('Third Term', 'Third Term')], default='First Term', max_length=20)),
                ('score', models.CharField(max_length=20)),
                ('out_of', models.IntegerField(default=100)),
                ('grade', models.CharField(choices=[('A', 'A (90% - 100%)'), ('B', 'B (80% - 89%)'), ('C', 'C (60% - 79%)'), ('D', 'D (0% - 59%)')], default='D', max_length=1)),
                ('year', models.IntegerField(default=2024)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_student', to='administration.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_subject', to='classes.subject')),
                ('teacher_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_teacher_class', to='teacher.teacherclass')),
            ],
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='FirstTest',
        ),
        migrations.DeleteModel(
            name='SecondTest',
        ),
    ]
