# Generated by Django 5.0.3 on 2024-09-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0048_rename_first_text_score_studentgrademodel_first_test_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgrademodel',
            name='exam_score',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentgrademodel',
            name='final_grade',
            field=models.CharField(blank=True, choices=[('A', 'A (90% - 100%)'), ('B', 'B (80% - 89%)'), ('C', 'C (60% - 79%)'), ('D', 'D (0% - 59%)')], default='D', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='studentgrademodel',
            name='second_test_score',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
