# Generated by Django 5.0.3 on 2024-09-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0049_alter_studentgrademodel_exam_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentgrademodel',
            old_name='final_grade',
            new_name='exam_final_grade',
        ),
        migrations.AddField(
            model_name='studentgrademodel',
            name='first_final_grade',
            field=models.CharField(blank=True, choices=[('A', 'A (90% - 100%)'), ('B', 'B (80% - 89%)'), ('C', 'C (60% - 79%)'), ('D', 'D (0% - 59%)')], default='D', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='studentgrademodel',
            name='second_final_grade',
            field=models.CharField(blank=True, choices=[('A', 'A (90% - 100%)'), ('B', 'B (80% - 89%)'), ('C', 'C (60% - 79%)'), ('D', 'D (0% - 59%)')], default='D', max_length=1, null=True),
        ),
    ]
