# Generated by Django 5.0.3 on 2024-09-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0050_rename_final_grade_studentgrademodel_exam_final_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgrademodel',
            name='first_final_grade',
        ),
        migrations.RemoveField(
            model_name='studentgrademodel',
            name='second_final_grade',
        ),
        migrations.AddField(
            model_name='studentgrademodel',
            name='first_test_grade',
            field=models.CharField(blank=True, choices=[('A', 'A (90% - 100%)'), ('B', 'B (80% - 89%)'), ('C', 'C (60% - 79%)'), ('D', 'D (0% - 59%)')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='studentgrademodel',
            name='second_test_grade',
            field=models.CharField(blank=True, choices=[('A', 'A (90% - 100%)'), ('B', 'B (80% - 89%)'), ('C', 'C (60% - 79%)'), ('D', 'D (0% - 59%)')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='studentgrademodel',
            name='exam_final_grade',
            field=models.CharField(blank=True, choices=[('A', 'A (90% - 100%)'), ('B', 'B (80% - 89%)'), ('C', 'C (60% - 79%)'), ('D', 'D (0% - 59%)')], max_length=1, null=True),
        ),
    ]
