# Generated by Django 5.0.3 on 2024-09-12 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_alter_teacher_subject'),
        ('classes', '0002_alter_class_subjects'),
        ('teacher', '0051_remove_studentgrademodel_first_final_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgrademodel',
            name='exam_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentgrademodel',
            name='first_test_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='studentgrademodel',
            name='second_test_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentgrademodel',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='administration.student'),
        ),
        migrations.AlterField(
            model_name='studentgrademodel',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_grades', to='classes.subject'),
        ),
        migrations.AlterField(
            model_name='studentgrademodel',
            name='teacher_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_grades', to='teacher.teacherclass'),
        ),
    ]
