# Generated by Django 5.0.3 on 2024-09-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0053_alter_studentgrademodel_exam_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentgrademodel',
            old_name='exam_final_grade',
            new_name='exam_grade',
        ),
        migrations.AddField(
            model_name='studentgrademodel',
            name='final_grade',
            field=models.CharField(blank=True, choices=[('A', 'A (90% - 100%)'), ('B', 'B (80% - 89%)'), ('C', 'C (60% - 79%)'), ('D', 'D (0% - 59%)')], max_length=1, null=True),
        ),
    ]
