# Generated by Django 5.0.3 on 2024-09-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0055_studentgrademodel_comment_studentgrademodel_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=300, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentgrademodel',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='studentgrademodel',
            name='position',
        ),
    ]
