# Generated by Django 5.0.3 on 2024-09-13 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0057_studentposition_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentposition',
            name='student',
        ),
    ]
