# Generated by Django 5.0.3 on 2024-09-15 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_class_subjects'),
        ('teacher', '0059_studentposition_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgrademodel',
            name='first_test_score',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentgrademodel',
            name='subject',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_grades', to='classes.subject'),
        ),
    ]
