# Generated by Django 5.0.3 on 2024-09-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0060_alter_studentgrademodel_first_test_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgrademodel',
            name='first_test_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
