# Generated by Django 5.0.3 on 2024-11-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0061_alter_studentgrademodel_first_test_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='term',
            field=models.CharField(choices=[('first_term', 'First Term'), ('second_term', 'Second Term'), ('third_term', 'Third Term')], default=False, max_length=50),
        ),
    ]
