# Generated by Django 5.0.3 on 2024-09-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0065_alter_attendance_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='term',
            field=models.CharField(blank=True, choices=[('First Term', 'First Term'), ('Second Term', 'Second Term'), ('Third Term', 'Third Term')], max_length=50),
        ),
    ]
