# Generated by Django 5.0.3 on 2024-09-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0066_alter_attendance_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='term',
            field=models.CharField(blank=True, choices=[('First Term', 'first_term'), ('Second Term', 'second_term'), ('Third Term', 'third_term')], max_length=50),
        ),
    ]
