# Generated by Django 5.0.3 on 2024-10-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0068_remove_attendance_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgrademodel',
            name='day',
            field=models.DateTimeField(auto_now_add=True, default=True),
            preserve_default=False,
        ),
    ]
