# Generated by Django 5.0.3 on 2024-10-23 07:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0068_remove_attendance_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgrademodel',
            name='day_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
