# Generated by Django 5.0.3 on 2024-10-27 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_class_subjects'),
        ('teacher', '0069_studentgrademodel_day_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('First Term', 'First Term'), ('Second Term', 'Second Term'), ('Third Term', 'Third Term')], default='First Term', max_length=20)),
                ('subject_date', models.CharField(max_length=200)),
                ('subject_topics', models.TextField()),
                ('classes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schemeofwork class +', to='classes.class')),
                ('subject', models.ManyToManyField(related_name='schemeofwork', to='classes.subject')),
                ('teacher_classes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_scheme', to='teacher.teacherclass')),
            ],
        ),
    ]
