# Generated by Django 5.0.3 on 2024-10-22 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0069_studentgrademodel_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentgrademodel',
            old_name='day',
            new_name='day_created',
        ),
    ]
