# Generated by Django 5.0.3 on 2024-10-22 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0070_rename_day_studentgrademodel_day_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgrademodel',
            name='day_created',
        ),
    ]
