# Generated by Django 5.0.3 on 2024-10-29 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0070_schemeofwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemeofwork',
            name='week',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='schemeofwork',
            name='subject_date',
            field=models.CharField(max_length=500),
        ),
    ]
