# Generated by Django 5.0.3 on 2024-10-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0071_remove_studentgrademodel_day_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgrademodel',
            name='day_created',
            field=models.DateField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
