# Generated by Django 5.0.3 on 2024-10-29 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0071_schemeofwork_week_alter_schemeofwork_subject_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemeofwork',
            name='week',
            field=models.CharField(default='Week 1', max_length=200),
        ),
    ]
