# Generated by Django 5.0.3 on 2024-10-29 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_class_subjects'),
        ('teacher', '0072_alter_schemeofwork_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schemeofwork',
            name='subject',
        ),
        migrations.AddField(
            model_name='schemeofwork',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schemeofwork', to='classes.subject'),
        ),
    ]
