# Generated by Django 5.0.3 on 2024-11-03 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0015_delete_schemeofwork'),
        ('teacher', '0073_remove_schemeofwork_subject_schemeofwork_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemeofwork',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schemes_of_work', to='administration.teacher'),
        ),
    ]
