# Generated by Django 5.0.3 on 2024-08-19 08:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_annoucement'),
    ]

    operations = [
        migrations.AddField(
            model_name='annoucement',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='annoucement',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
