# Generated by Django 5.0.3 on 2024-08-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_annoucement_date_posted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annoucement',
            name='subject',
            field=models.CharField(default=False, max_length=300),
            preserve_default=False,
        ),
    ]
