# Generated by Django 5.0.3 on 2024-08-05 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_remove_student_email_remove_teacher_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='last_name',
        ),
    ]
