# Generated by Django 5.0.3 on 2024-08-05 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_remove_student_first_name_remove_student_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='parent_name',
            new_name='parent_or_guildiance_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='parent_phone_number',
            new_name='parent_or_guildiance_phone_number',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='photo',
            new_name='profile_photo',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='photo',
            new_name='profile_photo',
        ),
    ]
