# Generated by Django 5.0.3 on 2024-08-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_rename_parent_name_student_parent_or_guildiance_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_photo',
            field=models.ImageField(default='default.jpg', upload_to='student_photos/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile_photo',
            field=models.ImageField(default='default.jpg', upload_to='teacher_photos/'),
        ),
    ]
