# Generated by Django 5.0.3 on 2024-09-29 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_remove_student_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodosList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
    ]
