# Generated by Django 5.0.3 on 2024-08-10 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_remove_student_profile_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='parent_or_guildiance_phone_number',
            new_name='parent_or_guardian_phone_number',
        ),
    ]
