# Generated by Django 5.0.3 on 2024-08-10 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_rename_parent_or_guildiance_phone_number_student_parent_or_guardian_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='parent_or_guildiance_name',
            new_name='parent_or_guardian_name',
        ),
    ]
