# Generated by Django 5.0.3 on 2024-09-29 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_todoslist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoslist',
            name='user',
        ),
    ]
