# Generated by Django 5.0.3 on 2024-10-27 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0014_schemeofwork'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchemeOfWork',
        ),
    ]
