# Generated by Django 5.0.3 on 2025-09-03 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0017_annoucement_recipient_type'),
        ('classes', '0002_alter_class_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAnnoucement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=1000)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('classes', models.ManyToManyField(related_name='teacher_announcement', to='classes.class')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_announcement', to='administration.teacher')),
            ],
        ),
    ]
