# Generated by Django 5.0.3 on 2025-09-03 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0018_teacherannoucement'),
        ('classes', '0002_alter_class_subjects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeacherAnnoucement',
            new_name='TeacherAnnouncement',
        ),
    ]
