# Generated by Django 5.0.3 on 2024-08-14 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_class_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='subjects',
            field=models.ManyToManyField(related_name='subjects', to='classes.subject'),
        ),
    ]
