# Generated by Django 5.0.3 on 2024-08-08 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(default='default.jpg', upload_to='profile_photo/'),
        ),
    ]
