# Generated by Django 5.0.3 on 2024-08-14 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_one_start_time', models.TimeField(blank=True, null=True)),
                ('subject_two_start_time', models.TimeField(blank=True, null=True)),
                ('subject_three_start_time', models.TimeField(blank=True, null=True)),
                ('subject_four_start_time', models.TimeField(blank=True, null=True)),
                ('subject_five_start_time', models.TimeField(blank=True, null=True)),
                ('subject_six_start_time', models.TimeField(blank=True, null=True)),
                ('subject_seven_start_time', models.TimeField(blank=True, null=True)),
                ('subject_one_end_time', models.TimeField(blank=True, null=True)),
                ('subject_two_end_time', models.TimeField(blank=True, null=True)),
                ('subject_three_end_time', models.TimeField(blank=True, null=True)),
                ('subject_four_end_time', models.TimeField(blank=True, null=True)),
                ('subject_five_end_time', models.TimeField(blank=True, null=True)),
                ('subject_six_end_time', models.TimeField(blank=True, null=True)),
                ('subject_seven_end_time', models.TimeField(blank=True, null=True)),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=10)),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='classes.class')),
                ('subject_five', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable5', to='classes.subject')),
                ('subject_four', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable4', to='classes.subject')),
                ('subject_one', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable1', to='classes.subject')),
                ('subject_seven', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable7', to='classes.subject')),
                ('subject_six', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable6', to='classes.subject')),
                ('subject_three', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable3', to='classes.subject')),
                ('subject_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable2', to='classes.subject')),
            ],
        ),
    ]
