# Generated by Django 5.0.3 on 2024-11-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='break_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='break_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
