# Generated by Django 5.0.3 on 2024-08-11 14:07

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_timetable_subject_timetable_subject_five_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='start_time',
        ),
        migrations.AddField(
            model_name='timetable',
            name='subject_five_end_time',
            field=models.TimeField(),
        ),
        migrations.AddField(
            model_name='timetable',
            name='subject_five_start_time',
            field=models.TimeField(),
        ),
        migrations.AddField(
            model_name='timetable',
            name='subject_four_end_time',
            field=models.TimeField(),
        ),
        migrations.AddField(
            model_name='timetable',
            name='subject_four_start_time',
            field=models.TimeField(),
        ),
        migrations.AddField(
            model_name='timetable',
            name='subject_one_end_time',
            field=models.TimeField(),
        ),
        migrations.AddField(
            model_name='timetable',
            name='subject_one_start_time',
            field=models.TimeField(),
        ),
        migrations.AddField(
            model_name='timetable',
            name='subject_seven_end_time',
            field=models.TimeField(),
        ),
        migrations.AddField(
            model_name='timetable',
            name='subject_seven_start_time',
            field=models.TimeField(),
        ),
        migrations.AddField(
            model_name='timetable',
            name='subject_six_end_time',
            field=models.TimeField(),
        ),
        migrations.AddField(
            model_name='timetable',
            name='subject_six_start_time',
            field=models.TimeField(),
        ),
        migrations.AddField(
            model_name='timetable',
            name='subject_three_end_time',
            field=models.TimeField(),
        ),
        migrations.AddField(
            model_name='timetable',
            name='subject_three_start_time',
            field=models.TimeField(),
        ),
        migrations.AddField(
            model_name='timetable',
            name='subject_two_end_time',
            field=models.TimeField(),
        ),
        migrations.AddField(
            model_name='timetable',
            name='subject_two_start_time',
            field=models.TimeField(),
        ),
    ]
