# Generated by Django 5.0.3 on 2024-11-24 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_class_subjects'),
        ('student', '0002_timetable_break_end_time_timetable_break_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='break_end_time',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='break_start_time',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='subject_five_end_time',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='subject_five_start_time',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='subject_four_end_time',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='subject_four_start_time',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='subject_one_end_time',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='subject_one_start_time',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='subject_seven_end_time',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='subject_seven_start_time',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='subject_six_end_time',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='subject_six_start_time',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='subject_three_end_time',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='subject_three_start_time',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='subject_two_end_time',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='subject_two_start_time',
        ),
        migrations.CreateModel(
            name='TimetableSubjectTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_start_time', models.TimeField(blank=True, null=True)),
                ('break_end_time', models.TimeField(blank=True, null=True)),
                ('subject_one_start_time', models.TimeField(blank=True, null=True)),
                ('subject_two_start_time', models.TimeField(blank=True, null=True)),
                ('subject_three_start_time', models.TimeField(blank=True, null=True)),
                ('subject_four_start_time', models.TimeField(blank=True, null=True)),
                ('subject_five_start_time', models.TimeField(blank=True, null=True)),
                ('subject_six_start_time', models.TimeField(blank=True, null=True)),
                ('subject_seven_start_time', models.TimeField(blank=True, null=True)),
                ('subject_one_end_time', models.TimeField(blank=True, null=True)),
                ('subject_two_end_time', models.TimeField(blank=True, null=True)),
                ('subject_three_end_time', models.TimeField(blank=True, null=True)),
                ('subject_four_end_time', models.TimeField(blank=True, null=True)),
                ('subject_five_end_time', models.TimeField(blank=True, null=True)),
                ('subject_six_end_time', models.TimeField(blank=True, null=True)),
                ('subject_seven_end_time', models.TimeField(blank=True, null=True)),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables_time', to='classes.class')),
            ],
        ),
    ]
