# Generated by Django 5.0.3 on 2024-08-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_timetable_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='subject_five_end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='subject_five_start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='subject_four_end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='subject_four_start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='subject_one_end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='subject_one_start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='subject_seven_end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='subject_seven_start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='subject_six_end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='subject_six_start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='subject_three_end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='subject_three_start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='subject_two_end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='subject_two_start_time',
            field=models.TimeField(),
        ),
    ]
